openapi: 3.0.3
info:
  title: Pricing API
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /price:
    get:
      tags:
        - http-input-adapter
      description: Return all prices
      operationId: getAll
      responses:
        '200':
          description: Exito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PriceResponse'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PriceResponse'
  /price/getByBrandAndProduct:
    get:
      tags:
        - http-input-adapter
      description: Returns the price filtered by product, brand and date of application
      operationId: getPriceByBrandAndProductInApplicationDate
      parameters:
        - name: applicationDate
          in: query
          required: false
          schema:
            type: string
        - name: productId
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: brandId
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          description: Identifier product code
          format: int64
          example: 35455
        brandId:
          type: integer
          description: Brand identifier
          format: int64
          example: 1
        priceList:
          type: integer
          description: Applicable price rate identifier
          format: int32
          example: 1
        startDate:
          type: string
          description: Start date of the date range to which the price rate applies
          format: date-time
        endDate:
          type: string
          description: End date of the date range in which the price rate applies
          format: date-time
        price:
          type: number
          description: Final sales price
          format: double
          example: 35.5
        currency:
          type: string
          description: ISO of the currency
          example: EUR
      description: Model representing the price consulted
